import type { Request, Response } from "express";
import { prisma } from "../config/db.js";
import { Prisma } from "../generated/prisma/client.js";

const createPr = async (req: Request, res: Response) => {
    const { exercise_title, remarks, weight, reps } = req.body
    const userId = req.userId

    // check if exercise already exists
    const exerciseExists = await prisma.pR.findUnique({
        where: {
            user_id_exercise_title: {
                user_id: userId!,
                exercise_title: exercise_title
            }
        }
    })
    if (exerciseExists) {
        return res.status(400).json({
            status: "failure",
            error: 'Exercise already exists'
        })
    }

    // PR => auto generated by columns weight and reps 

    // add new exercise
    const newExercise = await prisma.pR.create({
        data: {
            exercise_title,
            remarks,
            weight,
            reps,
            user_id: userId!
        },
        select: {
            id: true,
            exercise_title: true,
            remarks: true,
            weight: true,
            reps: true,
            PR: true
        }
    })

    // respond
    res.status(201).json({
        status: "success",
        data: { newExercise }
    })

}

const getAllPr = async (req: Request, res: Response) => {
    const userId = req.userId

    const prForUser = await prisma.pR.findMany({
        where: {
            user_id: userId!
        },
        select: {
            id: true,
            exercise_title: true,
            remarks: true,
            weight: true,
            reps: true,
            PR: true,
            updated_at: true
        }
    })

    res.status(200).json({
        status: "success",
        data: prForUser
    })
}

const getPrById = async (req: Request, res: Response) => {
    const prId = Number(req.params.id)
    const userId = req.userId

    const prForUser = await prisma.pR.findFirst({
        where: {
            user_id: userId!,
            id: prId
        },
        select: {
            id: true,
            exercise_title: true,
            remarks: true,
            weight: true,
            reps: true,
            PR: true,
            updated_at: true
        }
    })

    if (!prForUser) {
        return res.status(404).json({
            status: 'failure',
            error: `Exercise with id ${prId} not found`
        })
    }

    res.status(200).json({
        status: "success",
        data: prForUser
    })
}

const updatePrById = async (req: Request, res: Response) => {
    const prId = Number(req.params.id)
    const updateData = req.body
    
    let updatedPr
    try {
        updatedPr = await prisma.pR.update({
            where: {
                id: prId
            },
            data: updateData,
            select: {
                id: true,
                exercise_title: true,
                remarks: true,
                weight: true,
                reps: true,
                PR: true,
                updated_at: true
            }
        })
    } catch (error) {
        if (error instanceof Prisma.PrismaClientKnownRequestError) {
            if (error.code === 'P2025') {
                return res.status(404).json({
                    status: 'failure',
                    error: `Exercise with id ${prId} not found`
                })
            }
        }
        console.log(error)
        return res.status(500).json({
            status : 'success',
            error : 'Internal Server Error'
        })
    }

    res.status(200).json({
        status: 'success',
        data: updatedPr
    })
}
const prController = { createPr, getAllPr, getPrById, updatePrById }

export default prController